"""
Appendix figure: wrist time responses of each control strategy on the
nominal model, at rest and in deliberate motion.

Reads the nominal run of each strategy from results/runs (generated by
src/main.py) and plots the palm angle theta_3 against its voluntary
component theta_v3, one panel per strategy and scenario, on shared axes.

Run from the repository root:
    uv run cba-2026-presentation/figures/plot_time_responses.py
"""

import pickle

import blosc
import matplotlib.pyplot as plt
import numpy as np

OUT = "cba-2026-presentation/figures/time_responses.pdf"
RUNS = "results/runs/{}_amplitude_{}.data"

STRATEGIES = [
    ("uncontrolled", "Sem controle"),
    ("pid_imc", "IMC-PID"),
    ("pid_de", "DE-PID"),
    ("eadrc_ebmflc", "EADRC+EBMFLC"),
    ("eadrc_zplp", "EADRC+ZPLP"),
]
SCENARIOS = [("0.0", "Repouso"), ("1.0", "Movimento")]

# Slide theme colors (cba2026.sty)
PURPLE, GRAPHITE = "#7040B8", "#303030"

plt.rcParams.update(
    {
        "text.usetex": True,
        "font.family": "sans-serif",
        "text.latex.preamble": r"\usepackage{amsmath}\usepackage{sfmath}",
        "font.size": 11,
    }
)


def nominal_run(name: str, amplitude: str) -> dict:
    with open(RUNS.format(name, amplitude), "rb") as f:
        return pickle.loads(blosc.decompress(f.read()))["nominal_run"]


fig, axes = plt.subplots(
    len(STRATEGIES), len(SCENARIOS), figsize=(8.8, 4.0), sharex=True, sharey=True
)
for col, (amplitude, scenario) in enumerate(SCENARIOS):
    for row, (name, label) in enumerate(STRATEGIES):
        run = nominal_run(name, amplitude)
        t = run["time"]
        ax = axes[row, col]
        ax.plot(t, np.degrees(run["theta"][:, 2]), color=PURPLE, lw=0.5)
        ax.plot(t, np.degrees(run["theta_v"][:, 2]), color=GRAPHITE, lw=1.2, ls="--")
        ax.axhline(0, color="#B0B0B0", lw=0.5, zorder=0)
        ax.tick_params(length=2, labelsize=10, colors=GRAPHITE)
        for side in ("top", "right"):
            ax.spines[side].set_visible(False)
        if row == 0:
            ax.set_title(scenario, fontsize=13, color=GRAPHITE)
        if col == 0:
            ax.set_ylabel(label, fontsize=11, color=GRAPHITE, rotation=0, ha="right", va="center")

axes[0, 0].set_xlim(t[0], t[-1])
axes[0, 0].set_yticks([-60, 0, 60])
for ax in axes[-1]:
    ax.set_xlabel(r"Tempo [s]", fontsize=12, color=GRAPHITE)

handles = [
    plt.Line2D([], [], color=PURPLE, lw=1.2, label=r"$\theta_3$, resposta do punho [$^\circ$]"),
    plt.Line2D([], [], color=GRAPHITE, lw=1.2, ls="--", label=r"$\theta_{v_3}$, componente volunt\'aria [$^\circ$]"),
]
fig.legend(handles=handles, loc="lower center", ncol=2, frameon=False, fontsize=12,
           bbox_to_anchor=(0.55, -0.05), labelcolor=GRAPHITE)
fig.tight_layout(rect=(0, 0.06, 1, 1), h_pad=0.3)
fig.savefig(OUT, bbox_inches="tight", pad_inches=0.03)
print(f"Saved {OUT}")
